version: '3.3'
services:
  postgres:
    image: "postgres"
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/:/var/lib/postgresql/data/pgdata
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/
    environment:
       - "POSTGRES_USER=postgres"
       - "POSTGRES_PASSWORD=postgres"
       - "POSTGRES_DB=ammer"
       - "PGDATA=/var/lib/postgresql/data/pgdata" 
  spring:
    build:      
      context: .
      dockerfile: Dockerfile
    container_name: ammer-capital
    depends_on: 
      - "postgres"
    restart: always
    ports:
      - "8080:8080" 
      - "5005:5005"